### ISSUE TITLE
please update for forge 33.0.22

### ISSUE THREAD

**Issue by HonestAngel** [JSJBDEV/PlatosTransporters#18]
[mException in thread "main" [32m[09:12:01] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (PlatosTransporters-FORGE-1.16-1.2.4.jar)

get exit code 0

please add License...

**Comment by JSJBDEV** [comment]
Huh. That's a new one on me, are you running on 1.16.2?

**Comment by JSJBDEV** [comment]
Also the newest version of Plato's transporters is 1.3 but I do not believe any version supports 1.16.2 yet as there was an internal file change

**Comment by JSJBDEV** [comment]
yup, this is a specifically 1.16.2 issue just checked on the FML website I would have to push a new release to support it, so ill give it a shot

**Comment by JSJBDEV** [comment]
so ive just updated to forge 33 and there are things that are broken that really shouldnt be to do with ships becoming invisible and the airship not being able to go up, I am assuming this is because it is a buggy version of forge since ive just tested by build on 1.16.1 and it worked fine, so for the time being it will not be supported unless forge updates or I find a bug that causes it

**Comment by JSJBDEV** [comment]
ive appeared to get most things to work now but the way things break appears to be very random, I shall upload a 1.16.2 version and go from there

**Comment by JSJBDEV** [comment]
im going to close this issue now but it might end up being reopened due to other errors
