### ISSUE TITLE
Add Farmland to Blacklist

### ISSUE THREAD

**Issue by AlasEyrd** [JSJBDEV/PlatosTransporters#4]
Pretty straightforward, kinda important

**Comment by AlasEyrd** [comment]
If possible, could you use the vanilla tags for the blacklisted items? So the modded woods, leaves, etc can be blacklisted without manually changing the blacklist.json and recompiling?

**Comment by JSJBDEV** [comment]
Basically you can add a data pack yourself to change these things so you don't need to recompile, also the reason why #minecraft:logs isn't on the blacklist is because I felt they where fairly important in boat building so I excluding everything bar stripped logs. I can look into it but I went with the idea that it should be easy enough to find a biome without modded material to build ships in, then you can uses modded material

**Comment by JSJBDEV** [comment]
I will however definitely put farmland on that blacklist

**Comment by JSJBDEV** [comment]
logs are now fully excluded in the blacklist so mod logs should also be, farmland has also been added
