### ISSUE TITLE
Cannot disassemble a ship.

### ISSUE THREAD

**Issue by MattiT555** [JSJBDEV/PlatosTransporters#9]
Hello again, I've become sort of a beta tester for your mod, I reckon :-D.
When I try to dissasemble a ship, the game tells me there isn't enough space for that. I've attached a video of this issue. Out of 4 ships I've built, only one got disassembled properly.

[video with the issue.zip](https://github.com/JSJBDEV/PlatosTransporters/files/5011272/video.with.the.issue.zip)

**Comment by MattiT555** [comment]
Managed to disassemble the ship from the video after bringing it to dry land.

**Comment by JSJBDEV** [comment]
you cannot disassemble a ship on water. because technically you are "in" the water block, the disassembly algorithm needs air basically. I don't necessarily consider this a bug (it is not version specific and effects fabric too) but what I'll do is mark this issue as an enhancement so when I do need to build a new version I can consider adding this :D

**Comment by MattiT555** [comment]
Thanks for the info, and sorry for wasting your time!

**Comment by JSJBDEV** [comment]
dont worry its not a waste of time to report something you think is an issue, and it but be implemented anyway

**Comment by JSJBDEV** [comment]
this is now fully supported in all new versions, including water disassembly
